version: '3.9'

services:
  local-db:
    image: mysql:8.0.28-oracle
    container_name: samithiwat-user-db
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - ./volumes/database:/var/lib/mysql
    ports:
      - ${DATABASE_PORT}:3306

  local-cache:
    image: bitnami/redis:6.2.6
    container_name: samithiwat-user-cache
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - ${REDIS_PORT}:6379
